apiVersion: v1
kind: Pod
metadata:
  name: weight-node-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: gpu
            operator: In
            values:
            - intel
      - weight: 50
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - hdd
  containers:
  - name: weight-node
    image: nginx
