apiVersion: v1
kind: Pod
metadata:
  name: appusupport
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - appu
            - mon
        topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod
    image: nginx
