apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kin
  name: kin
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: env
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 100

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
