apiVersion: v1
data:
  index.html: |+

    <h1> Hello monish </h1>
    <h2> welcome buddy </h2>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-html
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp
  name: mon-pod
spec:
  containers:
  - image: nginx
    name: temp
    resources: {}
    envFrom:
    - configMapRef:
        name: app-config
    volumeMounts:
    - name: my-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-vol
    configMap:
      name: app-html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-26T05:32:55Z"
  labels:
    run: temp
  name: mon-pod
  namespace: test
  resourceVersion: "254125"
  uid: 8f88a190-da8e-40a6-9743-5c7764224ca2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.148.40
  clusterIPs:
  - 10.104.148.40
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30723
    port: 80
    protocol: TCP
  selector:
    run: temp
  sessionAffinity: None
  type: LoadBalancer

