apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myapp-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: myapp-volume
      persistentVolumeClaim:
        claimName: myapp-pvc
