apiVersion: v1
kind: Pod
metadata:
  name: ambassodor
spec:
  containers:
  - image: curlimages/curl
    name: test-container
    command: ["/bin/sh"]
    args: ["-c","while true;do curl localhost:8080;sleep 2;done"]
  - image: kunchalavikram/nginx-proxy:1.0
    name: proxy-container
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: kunchalavikram/flask-app:1.0
    name: pod
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flask
  name: flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask
status:
  loadBalancer: {}


