apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tester-db
  name: tester-db
spec:
  containers:
  - image: kunchalavikram/db-connector:1.0
    name: tester-db
    resources: {}
    envFrom:
    - secretRef:
       name: tester-db-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
