apiVersion: v1
data:
  password: UEFTU1dPUkQ9ImFkbWluMTIzIgo=
  username: TkFNRT0iTU9OSVNIIgo=
stringData:
  color: blue # now i can give the not-encoded data under stringData
  # internally k8s will convert this to encoded while storing
kind: Secret
metadata:
  creationTimestamp: null
  name: login

# kubectl create secret generic login --from-file=./password --from-file=./username --dry-run=client -o yaml > login-secret.yaml
