apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: login-pod
  name: login-pod-2
spec:
  containers:
  - image: nginx
    name: login-pod
    resources: {}
    env:
      - name: NAME
        valueFrom:
          secretKeyRef:
            name: login
            key: username
    env:
      - name: PASSW
        valueFrom:
          secretKeyRef:
            name: login
            key: password
  restartPolicy: Never
  dnsPolicy: ClusterFirst
status: {}

