apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-3
  name: pod-3
spec:
  containers:
  - image: nginx
    name: pod-3
    resources: {}
    volumeMounts:
    - name: share-vol
      mountPath: /usr/config
  volumes:
  - name: share-vol
    secret:
      secretName: login
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
