apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-2
  name: pod-2
spec:
  containers:
  - image: nginx
    name: pod-2
    resources: {}
    command: ["/bin/bash","-c"]
    args: ["printenv; sleep 2000"]
    envFrom:
    - secretRef:
       name: login
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
# this has envFrom that get complete data of secret as env into this pod
